sudo: false
cache:
  directories:
    - node_modules
notifications:
  email: true
language: node_js
node_js:
  - '10'
after_success:
  - npm run docs:build
  - git config --global user.name "TravisCI"
  - git config --global user.email "travisci@digitalbazaar.com"
  - npm run docs:publish